import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatExpansionModule } from '@angular/material/expansion';

@Component({
    selector: 'app-ai-disclaimer',
    imports: [CommonModule, MatExpansionModule],
    templateUrl: './ai-disclaimer.html',
    styleUrl: './ai-disclaimer.scss',
})
export class AiDisclaimer {
    @Input() visible: boolean = false;
    @Input() contentType: string = 'content';
    @Input() disclaimer: string = '';

    get bodyText(): string {
        if (this.disclaimer) return this.disclaimer;
        return `These ${this.contentType} are generated by a large language model (LLM) and may not always be accurate. The output can occasionally contain factual errors, hallucinations, awkward phrasing, or formatting issues due to the inherent limitations of AI text generation.`;
    }
}
